builders:
  scan_builder: # 扫描注解，放在缓存中
    import: "package:dartboot/core/builder/boot_builder.dart" # 路径需要修改为自己的项目的boot_builder文件路径
    builder_factories: ["scan"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: root_package
    build_to: cache
    runs_before: ['write_builder']
  write_builder: # 引入注解的类，输出dart文件
    import: "package:dartboot/core/builder/boot_builder.dart" # 路径需要修改为自己的项目的boot_builder文件路径
    builder_factories: ["write"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: root_package
    build_to: source