name: dartboot
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.github.com/luodongseu/dart-boot

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  mysql1: any
  analyzer: any
  dio: any
  uuid: any

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  source_gen: any
