name: dartboot
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.github.com/luodongseu/dart-boot

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  mysql1: any
  dio: any
  uuid: any
  analyzer: ^0.38.0

dev_dependencies:
  build_runner: any
#  build_web_compilers: ^2.3.0
  source_gen: any
