########################################################
# Eureka配置
eureka:
  zone: http://192.168.1.236:8008/eureka # eureka注册中心
  fetch-registry-interval-seconds: 5 # 刷新APP的周期（秒）
  heartbeat-interval-seconds: 5 # 心跳周期（秒）

########################################################
# 数据库配置
database:
  clickhouse:
    host: 192.168.1.225
    port: 8123
  mysql:
    host: 192.168.1.225
    port: 3306
    db: dev
    username: root
    password: root
    min-pool-size: 20
    max-pool-size: 50