########################################################
# profile配置
profile:
  active: dev

########################################################
# 应用配置
app:
  name: dartboot # 应用名可以自定义修改

########################################################
# 服务配置
server:
  port: 8700 # 端口可以自定义修改
  contextPath: /dartboot # 上下文可以自定义修改
