########################################################
# Eureka配置
eureka:
  zone: http://xxx.xxx.xx.xx:8008/eureka # eureka注册中心

########################################################
# 数据库配置
database:
  clickhouse:
    host: xxx.xxx.x.xx
    port: 8123
  mysql:
    host: xxx.xxx.x.xx
    port: 3306
    db: xxx
    username: xxx
    password: xxx
    minPoolSize: 20
    maxPoolSize: 50